version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER_ID
        - WWW_DATA_GROUP_ID
    ports:
     - ${HOST_HTTP_PORT}:80
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
     - .:/var/www
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${HOST_MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}



